server:
  port: 8081
spring:
  #配置主机
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456

  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据过期时间（30分钟）
  mail:
      host: smtp.qq.com
        # 你的QQ邮箱，这里为发件人，填自己的即可
      username: 1091871415@qq.com
        # 你的QQ邮箱授权码
      password: hzyhdsfyxdntgbag
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      #开启隐藏的提交方法,默认为false,配置了之后可以用delete和put方法提交
      hiddenmethod:
        filter:
          enabled: true
      thymeleaf:
        cache: false #关闭缓存
        content-type: text/html
        mode: LEGACYHTML5
reggie:
  path: D:\image\
  spring:

